name: new_recook
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #国际化支持
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: 9.2.0
  #包信息
  package_info: ^2.0.0
  #状态管理
  provider: ^5.0.0
  #屏幕适配
  flutter_screenutil: ^5.0.0+2
  #弹窗
  bot_toast: ^4.0.1
  #http
  dio: ^4.0.0
  #轮播图
  flutter_swiper_null_safety: ^1.0.2
  #支付宝支付功能
  tobias: ^2.1.0
  #微信支付
#  fluwx: ^3.6.1+4
  #路由相关
  get: ^4.6.2
  #各种扩展
  velocity_x: ^3.0.0
  #本地化存储
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  #调试信息输出
  power_logger: ^1.2.1
  #刷新组件
#  flutter_easyrefresh: ^2.2.1

  pull_to_refresh_flutter3: ^2.0.1
  #极光推送
#  jpush_flutter: ^2.1.5
  #高德地图相关
#  amap_flutter_map: ^3.0.0
  amap_flutter_location: ^3.0.0
  amap_flutter_base: ^3.0.0
  #model 自动生成注释插件
  json_annotation: ^4.0.1
  #瀑布流
  waterfall_flow: ^3.0.1
  #扩展组件
  expandable: ^5.0.1
  #加载网络图片
  cached_network_image: ^3.1.0
  #网页组件
  webview_flutter: ^2.0.13

  # 小数据缓存
  shared_preferences: ^2.0.6

  cupertino_icons: ^1.0.2

  #自动生成icon
  flutter_launcher_icons: ^0.9.2
  extended_text: ^5.0.4
  extended_image: ^3.0.0
  # 农历
  lunar_calendar_converter:
    1.0.4+1

  flutter_gifimage:
    git:
      url: https://github.com/peng8350/flutter_gifimage.git
      ref: 3dc34a11332e62be0e2d32649b3faa47b3bb778b

  scan: ^1.5.0
  images_picker: ^1.2.9

  #  common_utils: ^2.0.2
  #  decimal: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #导入包整理
  import_sorter: ^4.6.0
  hive_generator: ^1.1.0
  #脚本工具
  grinder: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  #model自动生成
  json_serializable: ^4.1.1
  build_runner: ^2.0.2
  pub_semver: ^2.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/

    #TODO 重构图片assets
    - assets/icons/
    - assets/images/
    - assets/webp/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.png"



